// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/spf/v1/spf.proto

package spfv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// These wire values are independent of the Go library's Result values.
type Result int32

const (
	Result_RESULT_UNSPECIFIED Result = 0
	Result_RESULT_NONE        Result = 1
	Result_RESULT_NEUTRAL     Result = 2
	Result_RESULT_PASS        Result = 3
	Result_RESULT_FAIL        Result = 4
	Result_RESULT_SOFTFAIL    Result = 5
	Result_RESULT_TEMPERROR   Result = 6
	Result_RESULT_PERMERROR   Result = 7
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "RESULT_NONE",
		2: "RESULT_NEUTRAL",
		3: "RESULT_PASS",
		4: "RESULT_FAIL",
		5: "RESULT_SOFTFAIL",
		6: "RESULT_TEMPERROR",
		7: "RESULT_PERMERROR",
	}
	Result_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"RESULT_NONE":        1,
		"RESULT_NEUTRAL":     2,
		"RESULT_PASS":        3,
		"RESULT_FAIL":        4,
		"RESULT_SOFTFAIL":    5,
		"RESULT_TEMPERROR":   6,
		"RESULT_PERMERROR":   7,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_api_spf_v1_spf_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_api_spf_v1_spf_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_api_spf_v1_spf_proto_rawDescGZIP(), []int{0}
}

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Literal IPv4 or IPv6 address of the SMTP client. Required.
	ClientIp string `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// Envelope sender; empty or "<>" means the null reverse path.
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// HELO/EHLO identity; required for null sender unless domain is set.
	Helo string `protobuf:"bytes,3,opt,name=helo,proto3" json:"helo,omitempty"`
	// Optional policy-domain override; otherwise derived from sender or HELO.
	Domain        string `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_spf_v1_spf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_spf_v1_spf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_spf_v1_spf_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *CheckRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *CheckRequest) GetHelo() string {
	if x != nil {
		return x.Helo
	}
	return ""
}

func (x *CheckRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CheckResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=spf.v1.Result" json:"result,omitempty"`
	// Untrusted DNS text. Never use directly as an SMTP response or log message.
	Explanation   string `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_spf_v1_spf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_spf_v1_spf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_spf_v1_spf_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_UNSPECIFIED
}

func (x *CheckResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_api_spf_v1_spf_proto protoreflect.FileDescriptor

const file_api_spf_v1_spf_proto_rawDesc = "" +
	"\n" +
	"\x14api/spf/v1/spf.proto\x12\x06spf.v1\"o\n" +
	"\fCheckRequest\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x12\n" +
	"\x04helo\x18\x03 \x01(\tR\x04helo\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\"Y\n" +
	"\rCheckResponse\x12&\n" +
	"\x06result\x18\x01 \x01(\x0e2\x0e.spf.v1.ResultR\x06result\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation*\xa8\x01\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vRESULT_NONE\x10\x01\x12\x12\n" +
	"\x0eRESULT_NEUTRAL\x10\x02\x12\x0f\n" +
	"\vRESULT_PASS\x10\x03\x12\x0f\n" +
	"\vRESULT_FAIL\x10\x04\x12\x13\n" +
	"\x0fRESULT_SOFTFAIL\x10\x05\x12\x14\n" +
	"\x10RESULT_TEMPERROR\x10\x06\x12\x14\n" +
	"\x10RESULT_PERMERROR\x10\a2B\n" +
	"\n" +
	"SPFService\x124\n" +
	"\x05Check\x12\x14.spf.v1.CheckRequest\x1a\x15.spf.v1.CheckResponseB)Z'github.com/zaccone/spf/api/spf/v1;spfv1b\x06proto3"

var (
	file_api_spf_v1_spf_proto_rawDescOnce sync.Once
	file_api_spf_v1_spf_proto_rawDescData []byte
)

func file_api_spf_v1_spf_proto_rawDescGZIP() []byte {
	file_api_spf_v1_spf_proto_rawDescOnce.Do(func() {
		file_api_spf_v1_spf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_spf_v1_spf_proto_rawDesc), len(file_api_spf_v1_spf_proto_rawDesc)))
	})
	return file_api_spf_v1_spf_proto_rawDescData
}

var file_api_spf_v1_spf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_spf_v1_spf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_spf_v1_spf_proto_goTypes = []any{
	(Result)(0),           // 0: spf.v1.Result
	(*CheckRequest)(nil),  // 1: spf.v1.CheckRequest
	(*CheckResponse)(nil), // 2: spf.v1.CheckResponse
}
var file_api_spf_v1_spf_proto_depIdxs = []int32{
	0, // 0: spf.v1.CheckResponse.result:type_name -> spf.v1.Result
	1, // 1: spf.v1.SPFService.Check:input_type -> spf.v1.CheckRequest
	2, // 2: spf.v1.SPFService.Check:output_type -> spf.v1.CheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_spf_v1_spf_proto_init() }
func file_api_spf_v1_spf_proto_init() {
	if File_api_spf_v1_spf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_spf_v1_spf_proto_rawDesc), len(file_api_spf_v1_spf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_spf_v1_spf_proto_goTypes,
		DependencyIndexes: file_api_spf_v1_spf_proto_depIdxs,
		EnumInfos:         file_api_spf_v1_spf_proto_enumTypes,
		MessageInfos:      file_api_spf_v1_spf_proto_msgTypes,
	}.Build()
	File_api_spf_v1_spf_proto = out.File
	file_api_spf_v1_spf_proto_goTypes = nil
	file_api_spf_v1_spf_proto_depIdxs = nil
}
