// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/spf/v1/spf.proto

package spfv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SPFService_Check_FullMethodName = "/spf.v1.SPFService/Check"
)

// SPFServiceClient is the client API for SPFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SPFService evaluates SPF; mail acceptance policy belongs to the caller.
type SPFServiceClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type sPFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSPFServiceClient(cc grpc.ClientConnInterface) SPFServiceClient {
	return &sPFServiceClient{cc}
}

func (c *sPFServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, SPFService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SPFServiceServer is the server API for SPFService service.
// All implementations must embed UnimplementedSPFServiceServer
// for forward compatibility.
//
// SPFService evaluates SPF; mail acceptance policy belongs to the caller.
type SPFServiceServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedSPFServiceServer()
}

// UnimplementedSPFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSPFServiceServer struct{}

func (UnimplementedSPFServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedSPFServiceServer) mustEmbedUnimplementedSPFServiceServer() {}
func (UnimplementedSPFServiceServer) testEmbeddedByValue()                    {}

// UnsafeSPFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SPFServiceServer will
// result in compilation errors.
type UnsafeSPFServiceServer interface {
	mustEmbedUnimplementedSPFServiceServer()
}

func RegisterSPFServiceServer(s grpc.ServiceRegistrar, srv SPFServiceServer) {
	// If the following call panics, it indicates UnimplementedSPFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SPFService_ServiceDesc, srv)
}

func _SPFService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SPFServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SPFService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SPFServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SPFService_ServiceDesc is the grpc.ServiceDesc for SPFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SPFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spf.v1.SPFService",
	HandlerType: (*SPFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _SPFService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/spf/v1/spf.proto",
}
