#!/usr/bin/env python3
"""Regenerate test-only JSON from vendored pySPF YAML (PyYAML 6.0.3).

Source YAML and license notices are unchanged. This converter is project code,
not a copy of pySPF's Python test driver. No Python dependency is needed by Go.
"""
import argparse
import hashlib
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1] / "testdata" / "pyspf"
REVISION = "1042e9e15dd29047dc9b0a1bb77437e2fd81e775"
SOURCE_HASHES = {'rfc7208-tests.yml': '901f561a6e2b1c1590a40a61b1ac7601226fd7045a7aae591a4d25421358d6f9', 'test.yml': '180fe83dd5b71ccd76d9d428deec4fa0afd6d75f5f9a7df473dc21c310ceba27'}

LICENSE_HASHES = {'pyspf.LICENSE': 'f98f108da28af1ea6e3a143ca64c96859b7aa4b380a93289dc865fb458d7e035', 'rfc7208-tests.LICENSE': '5f0966386999bf30ee03e02ee9caab8752ae1aefad317bd6e0646ba636f3e111'}

def write_or_check(path, contents, check):
    if check:
        if path.read_text() != contents:
            raise SystemExit(f"Generated file is stale: {path}")
    else:
        path.write_text(contents)



def convert(filename, check):
    source = ROOT / filename
    if hashlib.sha256(source.read_bytes()).hexdigest() != SOURCE_HASHES[filename]:
        raise SystemExit(f"Pinned source changed: {source}")
    scenarios = []
    for group in yaml.safe_load_all(source.read_text()):
        tests = {}
        for name, case in group["tests"].items():
            case = dict(case)
            case["result"] = case["result"] if isinstance(case["result"], list) else [case["result"]]
            if "spec" in case:
                case["spec"] = str(case["spec"])
            tests[name] = case
        zone = {}
        for name, records in group["zonedata"].items():
            # The upstream suite uses SPF as shorthand for TXT unless the
            # owner explicitly supplies TXT (including the NONE sentinel).
            explicit_txt = any(isinstance(rr, dict) and "TXT" in rr for rr in records)
            converted = []
            for rr in records:
                if rr == "TIMEOUT":
                    converted.append({"type": "TIMEOUT"})
                    continue
                for kind, value in rr.items():
                    if kind == "SPF":
                        if explicit_txt:
                            continue
                        kind = "TXT"
                    if kind == "TXT":
                        value = [value] if isinstance(value, str) else value
                        if value == ["NONE"]:
                            continue
                        converted.append({"type": kind, "text": value})
                    elif kind == "MX":
                        converted.append({"type": kind, "preference": value[0], "value": value[1]})
                    elif kind in ("A", "AAAA", "PTR", "CNAME"):
                        converted.append({"type": kind, "value": value})
                    else:
                        raise ValueError(f"unsupported DNS record: {rr}")
            zone[name.lower().rstrip(".")] = converted
        scenarios.append({"description": group.get("description", group.get("comment", "")), "tests": tests, "zone": zone})
    output = {"revision": REVISION, "source": filename, "sha256": hashlib.sha256(source.read_bytes()).hexdigest(), "scenarios": scenarios}
    write_or_check(ROOT / (source.stem + ".json"), json.dumps(output, indent=2, ensure_ascii=True, sort_keys=True) + "\n", check)
    return output



def write_matrix(corpora, check):
    dispositions = json.loads((ROOT / "dispositions.json").read_text())
    rows = ["# Corpus case inventory", "", "Generated by `tools/import_pyspf.py`; all source cases are listed. Results are", "upstream accepted results, not a claim about every resolver backend. See", "[CONFORMANCE.md](../../CONFORMANCE.md) for the runner contract and limitations.", "", "| Case | Accepted result(s) | Assertion scope |", "| --- | --- | --- |"]
    for corpus in corpora:
        suite = Path(corpus["source"]).stem
        for scenario in corpus["scenarios"]:
            for name, case in sorted(scenario["tests"].items()):
                key = suite + "/" + name
                disposition = dispositions.get(key, {})
                scope = "Result" + (" + explanation" if "explanation" in case else "")
                if disposition.get("skip"):
                    scope = "Excluded: " + disposition["reason"]
                elif disposition:
                    scope += "; " + disposition["reason"]
                if case.get("explanation") == "DEFAULT":
                    scope += "; DEFAULT maps to this API's empty fallback"
                rows.append(f"| `{key}` | {', '.join(case['result'])} | {scope} |")
    write_or_check(ROOT / "CASES.md", "\n".join(rows) + "\n", check)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check generated files without writing")
    args = parser.parse_args()
    for filename, expected in LICENSE_HASHES.items():
        if hashlib.sha256((ROOT / filename).read_bytes()).hexdigest() != expected:
            raise SystemExit(f"Pinned license changed: {filename}")
    corpora = [convert(filename, args.check) for filename in SOURCE_HASHES]
    write_matrix(corpora, args.check)
    files = sorted(list(SOURCE_HASHES) + list(LICENSE_HASHES) + ["rfc7208-tests.json", "test.json", "dispositions.json", "CASES.md"])
    checksums = "".join(hashlib.sha256((ROOT / name).read_bytes()).hexdigest() + "  " + name + "\n" for name in files)
    write_or_check(ROOT / "SHA256SUMS", checksums, args.check)
